=== StudentsAgainstCovid19/corona-aid/src/dtd/config.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Set (item)*>
<!ELEMENT item (id,configKey,configValue)>

<!ELEMENT id (#PCDATA)>
<!ELEMENT configKey (#PCDATA)>
<!ELEMENT configValue (#PCDATA)>

=== StudentsAgainstCovid19/corona-aid/src/xml_examples/config_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Set SYSTEM "dtd/config.dtd">
<Set>
    <item>
        <id>3</id>
        <configKey>autoResetOffset</configKey>
        <configValue>15</configValue>
    </item>
    <item>
        <id>4</id>
        <configKey>standardLat</configKey>
        <configValue>49.013868</configValue>
    </item>
    <item>
        <id>5</id>
        <configKey>standardLon</configKey>
        <configValue>8.404346</configValue>
    </item>
    <item>
        <id>6</id>
        <configKey>clusteredDistance</configKey>
        <configValue>100</configValue>
    </item>
    <item>
        <id>7</id>
        <configKey>pieChartScaleConstant</configKey>
        <configValue>0.4</configValue>
    </item>
    <item>
        <id>8</id>
        <configKey>markerScale</configKey>
        <configValue>0.3</configValue>
    </item>
    <item>
        <id>9</id>
        <configKey>standardZoom</configKey>
        <configValue>13</configValue>
    </item>
    <item>
        <id>10</id>
        <configKey>zoomChange</configKey>
        <configValue>0.5</configValue>
    </item>
    <item>
        <id>11</id>
        <configKey>animationDuration</configKey>
        <configValue>200</configValue>
    </item>
    <item>
        <id>12</id>
        <configKey>closeContinueSearchTime</configKey>
        <configValue>20000</configValue>
    </item>
    <item>
        <id>13</id>
        <configKey>realtimeRefreshInterval</configKey>
        <configValue>15</configValue>
    </item>
    <item>
        <id>14</id>
        <configKey>frontendRefreshIntervall</configKey>
        <configValue>10000</configValue>
    </item>
    <item>
        <id>15</id>
        <configKey>pieChartScaleLinear</configKey>
        <configValue>0.0005</configValue>
    </item>
    <item>
        <id>16</id>
        <configKey>projectionType</configKey>
        <configValue>EPSG:3857</configValue>
    </item>
</Set>
