=== StudentsAgainstCovid19/corona-aid/src/dtd/infected_id.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT InfectedDto (contactData,tests,initialDiseases,historyItems,
                       age,updateFlag,id,forename,surname,birthDate,
                       city,postalCode,street,houseNumber,lat,lon,
                       healthInsuranceNumber,done)>

<!ELEMENT contactData (contactItem)*>
<!ELEMENT contactItem (id,contactKey,contactValue)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT contactKey (#PCDATA)>
<!ELEMENT contactValue (#PCDATA)>

<!ELEMENT tests (test)*>
<!ELEMENT test (daysOverdue,id,infectedId,timestamp,result)>
<!ELEMENT daysOverdue (#PCDATA)>
<!ELEMENT infectedId (#PCDATA)>
<!ELEMENT timestamp (#PCDATA)>
<!ELEMENT result (#PCDATA)>

<!ELEMENT initialDiseases (initialDisease)*>
<!ELEMENT initialDisease (id, name, degreeOfDanger, probability)>

<!ELEMENT historyItems (historyItem)*>
<!ELEMENT historyItem (symptoms,date,id,infectedId,timestamp,status,
                       personalFeeling,notes)>
<!ELEMENT symptoms (symptom)*>
<!ELEMENT symptom (id,name,degreeOfDanger,probability)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT degreeOfDanger (#PCDATA)>
<!ELEMENT probability (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT personalFeeling (#PCDATA)>
<!ELEMENT notes (#PCDATA)>

<!ELEMENT age (#PCDATA)>
<!ELEMENT updateFlag (#PCDATA)>
<!ELEMENT forename (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT birthDate (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT houseNumber (#PCDATA)>
<!ELEMENT lat (#PCDATA)>
<!ELEMENT lon (#PCDATA)>
<!ELEMENT healthInsuranceNumber (#PCDATA)>
<!ELEMENT done (#PCDATA)>

=== StudentsAgainstCovid19/corona-aid/src/xml_examples/infected_id_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE InfectedDto SYSTEM "https://www.corona-aid-ka.de/dtd/infected_id.dtd">
<InfectedDto>
	<contactData>
		<contactItem>
			<id>373</id>
			<contactKey>phone</contactKey>
			<contactValue>0721 53714359</contactValue>
		</contactItem>
	</contactData>
	<tests>
		<test>
			<daysOverdue>17</daysOverdue>
			<id>277</id>
			<infectedId>373</infectedId>
			<timestamp>1593765906489</timestamp>
			<result>2</result>
		</test>
	</tests>
	<initialDiseases />
	<historyItems>
		<historyItem>
			<symptoms />
			<date>Montag, 13. Juli 2020</date>
			<id>11393</id>
			<infectedId>373</infectedId>
			<timestamp>1594591204791</timestamp>
			<status>1</status>
			<personalFeeling>1</personalFeeling>
			<notes />
		</historyItem>
		<historyItem>
			<symptoms />
			<date>Dienstag, 14. Juli 2020</date>
			<id>13632</id>
			<infectedId>373</infectedId>
			<timestamp>1594677607613</timestamp>
			<status>1</status>
			<personalFeeling>4</personalFeeling>
			<notes />
		</historyItem>
		<historyItem>
			<symptoms />
			<date>Dienstag, 14. Juli 2020</date>
			<id>13647</id>
			<infectedId>373</infectedId>
			<timestamp>1594677607712</timestamp>
			<status>2</status>
			<personalFeeling>1</personalFeeling>
			<notes />
		</historyItem>
		<historyItem>
			<symptoms />
			<date>Mittwoch, 15. Juli 2020</date>
			<id>14333</id>
			<infectedId>373</infectedId>
			<timestamp>1594764009692</timestamp>
			<status>0</status>
			<personalFeeling>4</personalFeeling>
			<notes />
		</historyItem>
		<historyItem>
			<symptoms />
			<date>Donnerstag, 16. Juli 2020</date>
			<id>14833</id>
			<infectedId>373</infectedId>
			<timestamp>1594850407523</timestamp>
			<status>2</status>
			<personalFeeling>1</personalFeeling>
			<notes />
		</historyItem>
	</historyItems>
	<age>75</age>
	<updateFlag>false</updateFlag>
	<id>373</id>
	<forename>Marta</forename>
	<surname>Rausch</surname>
	<birthDate>1944-09-22</birthDate>
	<city>Karlsruhe</city>
	<postalCode>76131</postalCode>
	<street>Ernststra√üe</street>
	<houseNumber>61</houseNumber>
	<lat>49.01422</lat>
	<lon>8.44414</lon>
	<healthInsuranceNumber>V219594113</healthInsuranceNumber>
	<done>false</done>
</InfectedDto>
