=== StudentsAgainstCovid19/corona-aid/src/dtd/push_history_item.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT History (infectedId,notes,personalFeeling,status,symptoms,
                   timestamp)>
<!ELEMENT infectedId (#PCDATA)>
<!ELEMENT notes EMPTY>
<!ELEMENT personalFeeling (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT symptoms (symptom)+>
<!ELEMENT symptom (#PCDATA)>
<!ELEMENT timestamp (#PCDATA)>

=== StudentsAgainstCovid19/corona-aid/src/xml_examples/push_history_item_example.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE History SYSTEM "https://corona-aid-ka.de/dtd/push_history_item.dtd">
<History>
	<infectedId>857</infectedId>
	<notes></notes>
	<personalFeeling>4</personalFeeling>
	<status>1</status>
	<symptoms>
		<symptom>2</symptom>
		<symptom>3</symptom>
		<symptom>4</symptom>
		<symptom>10</symptom>
	</symptoms>
	<timestamp>1595523158922</timestamp>
</History>
